import customtkinter as ctk
from tkinter import filedialog, messagebox
from PIL import Image
import os
from gradio_client import Client, handle_file
import threading
import shutil
import webbrowser
import requests
import json
import time

# Set appearance mode and color theme
ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("blue")

class VideoApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.title("AI Video Generator")
        self.geometry("600x780")
        self.resizable(False, False)

        self.image_path = None

        # --- UI Elements ---
        
        # 0. Backend Mode
        self.mode_label = ctk.CTkLabel(self, text="0. Select Processing Mode:", font=("Arial", 14, "bold"))
        self.mode_label.pack(pady=(20, 5), padx=20, anchor="w")
        
        self.mode_var = ctk.StringVar(value="Cloud (Colab)")
        self.mode_radio_cloud = ctk.CTkRadioButton(self, text="Cloud (Colab) - Uses internet, no GPU needed", variable=self.mode_var, value="Cloud (Colab)", command=self.toggle_mode)
        self.mode_radio_cloud.pack(pady=5, padx=20, anchor="w")
        
        self.mode_radio_local = ctk.CTkRadioButton(self, text="Local (ComfyUI) - Uses your GTX 1070 Ti (SVD only)", variable=self.mode_var, value="Local (ComfyUI)", command=self.toggle_mode)
        self.mode_radio_local.pack(pady=5, padx=20, anchor="w")

        # 1. Colab Open Button
        self.colab_label = ctk.CTkLabel(self, text="1. Open Cloud Environment:", font=("Arial", 14, "bold"))
        self.colab_label.pack(pady=(15, 5), padx=20, anchor="w")
        
        self.colab_btn = ctk.CTkButton(self, text="🌐 Open Google Colab", 
                                       command=lambda: webbrowser.open("https://colab.research.google.com/"),
                                       fg_color="green", hover_color="darkgreen")
        self.colab_btn.pack(pady=5, padx=20, anchor="w")

        # 2. Gradio URL
        self.url_label = ctk.CTkLabel(self, text="2. Paste Gradio Link (generated by Colab):", font=("Arial", 14, "bold"))
        self.url_label.pack(pady=(15, 5), padx=20, anchor="w")
        
        self.url_entry = ctk.CTkEntry(self, placeholder_text="https://xxxxxx.gradio.live", width=560)
        self.url_entry.pack(pady=5, padx=20)

        # 3. Model Selection
        self.model_label = ctk.CTkLabel(self, text="3. Select AI Model:", font=("Arial", 14, "bold"))
        self.model_label.pack(pady=(15, 5), padx=20, anchor="w")
        
        self.model_var = ctk.StringVar(value="Stable Video Diffusion (Image-to-Video)")
        self.model_dropdown = ctk.CTkOptionMenu(self, variable=self.model_var, 
                                                values=[
                                                    "Stable Video Diffusion (Image-to-Video)", 
                                                    "LTX-Video 2.3 (Text-to-Video)",
                                                    "LTX-Video 2.3 (Custom Style)"
                                                ],
                                                width=560)
        self.model_dropdown.pack(pady=5, padx=20)

        # 4. Image Upload
        self.image_label = ctk.CTkLabel(self, text="4. Select Starting Image (for SVD):", font=("Arial", 14, "bold"))
        self.image_label.pack(pady=(15, 5), padx=20, anchor="w")
        
        self.image_btn = ctk.CTkButton(self, text="Browse Image", command=self.select_image, fg_color="gray40", hover_color="gray30")
        self.image_btn.pack(pady=5, padx=20, anchor="w")
        
        self.image_preview_label = ctk.CTkLabel(self, text="No image selected")
        self.image_preview_label.pack(pady=5, padx=20, anchor="w")

        # 5. Prompt
        self.prompt_label = ctk.CTkLabel(self, text="5. Enter Prompt (for LTX):", font=("Arial", 14, "bold"))
        self.prompt_label.pack(pady=(15, 5), padx=20, anchor="w")
        
        self.prompt_entry = ctk.CTkTextbox(self, height=60, width=560)
        self.prompt_entry.pack(pady=5, padx=20)

        # 6. Generate Button
        self.generate_btn = ctk.CTkButton(self, text="🚀 Generate Video", command=self.start_generation, height=50, font=("Arial", 16, "bold"))
        self.generate_btn.pack(pady=(20, 10), padx=20)
        
        self.status_label = ctk.CTkLabel(self, text="", text_color="yellow", font=("Arial", 12))
        self.status_label.pack(pady=5, padx=20)

        self.toggle_mode()

    def toggle_mode(self):
        mode = self.mode_var.get()
        if mode == "Local (ComfyUI)":
            self.url_entry.configure(state="disabled")
            self.colab_btn.configure(state="disabled")
            # Force SVD model since local LTX is too heavy
            self.model_var.set("Stable Video Diffusion (Image-to-Video)")
            self.model_dropdown.configure(state="disabled")
            self.prompt_entry.configure(state="disabled")
        else:
            self.url_entry.configure(state="normal")
            self.colab_btn.configure(state="normal")
            self.model_dropdown.configure(state="normal")
            self.prompt_entry.configure(state="normal")

    def select_image(self):
        file_path = filedialog.askopenfilename(filetypes=[("Image Files", "*.png *.jpg *.jpeg")])
        if file_path:
            self.image_path = file_path
            self.image_preview_label.configure(text=f"Selected: {os.path.basename(file_path)}")

    def start_generation(self):
        mode = self.mode_var.get()
        url = self.url_entry.get().strip()
        model = self.model_var.get()
        prompt = self.prompt_entry.get("1.0", "end-1c").strip()
        image = self.image_path

        if mode == "Cloud (Colab)":
            if not url:
                messagebox.showerror("Error", "Please paste the Gradio Link first!")
                return
            if "colab.research.google.com" in url or "huggingface.co" in url:
                messagebox.showerror("Wrong Link", "Oops! You pasted the Google Colab Notebook link.\n\nYou need to paste the Gradio Live link.\n1. Click the Open Colab button.\n2. In Colab, click 'Run All'.\n3. Wait for the cell at the bottom to finish loading.\n4. Copy the link that looks like 'https://xxxxxx.gradio.live' and paste it here.")
                return

        if "Stable Video Diffusion" in model and not image:
            messagebox.showerror("Error", "Please select an image for SVD!")
            return
            
        if mode == "Cloud (Colab)" and "LTX-Video" in model and not prompt:
            messagebox.showerror("Error", "Please enter a prompt for LTX-Video!")
            return

        self.generate_btn.configure(state="disabled", text="⏳ Generating... Please wait (might take minutes)")
        
        if mode == "Cloud (Colab)":
            self.status_label.configure(text="Sending request to Colab...")
            threading.Thread(target=self.generate_cloud_task, args=(url, model, prompt, image), daemon=True).start()
        else:
            self.status_label.configure(text="Sending request to Local ComfyUI...")
            threading.Thread(target=self.generate_local_task, args=(image,), daemon=True).start()

    def generate_cloud_task(self, url, model, prompt, image):
        try:
            client = Client(url)
            self.status_label.configure(text="Processing on cloud GPU...")
            
            img_input = handle_file(image) if image else None
            result_video_path = client.predict(
                image=img_input,
                prompt=prompt,
                model_choice=model,
                api_name="/predict"
            )
            
            self.save_video(result_video_path)
        except Exception as e:
            self.status_label.configure(text="❌ Error occurred")
            self.after(0, lambda e_msg=str(e): messagebox.showerror("Generation Error", f"Could not generate video on cloud.\nError: {e_msg}"))
        finally:
            self.generate_btn.configure(state="normal", text="🚀 Generate Video")

    def generate_local_task(self, image_path):
        try:
            comfy_url = "http://127.0.0.1:8000"
            app_folder = os.path.dirname(os.path.abspath(__file__))
            workflow_path = os.path.join(app_folder, "SVD_Workflow.json")
            
            if not os.path.exists(workflow_path):
                raise Exception("SVD_Workflow.json not found in app folder.")

            self.status_label.configure(text="Uploading image to Local ComfyUI...")
            
            # 1. Upload Image
            with open(image_path, "rb") as f:
                res = requests.post(f"{comfy_url}/upload/image", files={"image": f})
            if res.status_code != 200:
                raise Exception(f"Failed to upload image. Is ComfyUI running? {res.text}")
            uploaded_filename = res.json()["name"]

            # 2. Load and modify workflow
            with open(workflow_path, "r", encoding="utf-8") as f:
                workflow = json.load(f)
                
            # Set the image node
            workflow["1"]["inputs"]["image"] = uploaded_filename

            # 3. Queue Prompt
            self.status_label.configure(text="Processing on Local GTX 1070 Ti...")
            p = {"prompt": workflow}
            res = requests.post(f"{comfy_url}/prompt", json=p)
            if res.status_code != 200:
                raise Exception(f"Failed to queue prompt: {res.text}")
            
            prompt_id = res.json()["prompt_id"]

            # 4. Poll history until done
            output_filename = None
            while True:
                time.sleep(2)
                h_res = requests.get(f"{comfy_url}/history/{prompt_id}")
                if h_res.status_code == 200:
                    history = h_res.json()
                    if prompt_id in history:
                        outputs = history[prompt_id].get("outputs", {})
                        if "7" in outputs and "gifs" in outputs["7"]:
                            output_filename = outputs["7"]["gifs"][0]["filename"]
                            break
                        else:
                            raise Exception("No video generated in the output nodes.")

            # 5. Download the video
            self.status_label.configure(text="Downloading video from ComfyUI...")
            vid_res = requests.get(f"{comfy_url}/view?filename={output_filename}&type=output")
            
            temp_vid = os.path.join(app_folder, "temp_local.mp4")
            with open(temp_vid, "wb") as f:
                f.write(vid_res.content)

            self.save_video(temp_vid)

        except Exception as e:
            self.status_label.configure(text="❌ Error occurred")
            self.after(0, lambda e_msg=str(e): messagebox.showerror("Generation Error", f"Could not generate locally.\nError: {e_msg}"))
        finally:
            self.generate_btn.configure(state="normal", text="🚀 Generate Video")

    def save_video(self, source_path):
        app_folder = os.path.dirname(os.path.abspath(__file__))
        final_path = os.path.join(app_folder, "Generated_Video.mp4")
        
        counter = 1
        while os.path.exists(final_path):
            final_path = os.path.join(app_folder, f"Generated_Video_{counter}.mp4")
            counter += 1
            
        shutil.copy(source_path, final_path)
        self.status_label.configure(text=f"✅ Done! Saved as {os.path.basename(final_path)}")
        self.after(0, lambda p=final_path: messagebox.showinfo("Success!", f"Video generated and saved in the app folder as:\n{os.path.basename(p)}"))

if __name__ == "__main__":
    app = VideoApp()
    app.mainloop()