import customtkinter as ctk
from tkinter import filedialog, messagebox
from PIL import Image
import os
from gradio_client import Client, handle_file
import threading
import shutil
import webbrowser

# Set appearance mode and color theme
ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("blue")

class VideoApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.title("AI Video Generator")
        self.geometry("600x700")
        self.resizable(False, False)

        self.image_path = None

        # --- UI Elements ---
        
        # 1. Colab Open Button
        self.colab_label = ctk.CTkLabel(self, text="1. Open Cloud Environment:", font=("Arial", 14, "bold"))
        self.colab_label.pack(pady=(20, 5), padx=20, anchor="w")
        
        self.colab_btn = ctk.CTkButton(self, text="🌐 Open Google Colab", 
                                       command=lambda: webbrowser.open("https://colab.research.google.com/"),
                                       fg_color="green", hover_color="darkgreen")
        self.colab_btn.pack(pady=5, padx=20, anchor="w")

        # 2. Gradio URL
        self.url_label = ctk.CTkLabel(self, text="2. Paste Gradio Link (generated by Colab):", font=("Arial", 14, "bold"))
        self.url_label.pack(pady=(15, 5), padx=20, anchor="w")
        
        self.url_entry = ctk.CTkEntry(self, placeholder_text="https://xxxxxx.gradio.live", width=560)
        self.url_entry.pack(pady=5, padx=20)

        # 3. Model Selection
        self.model_label = ctk.CTkLabel(self, text="3. Select AI Model:", font=("Arial", 14, "bold"))
        self.model_label.pack(pady=(20, 5), padx=20, anchor="w")
        
        self.model_var = ctk.StringVar(value="Stable Video Diffusion (Image-to-Video)")
        self.model_dropdown = ctk.CTkOptionMenu(self, variable=self.model_var, 
                                                values=[
                                                    "Stable Video Diffusion (Image-to-Video)", 
                                                    "LTX-Video 2.3 (Text-to-Video)",
                                                    "LTX-Video 2.3 (Custom Style)"
                                                ],
                                                width=560)
        self.model_dropdown.pack(pady=5, padx=20)

        # 3. Image Upload
        self.image_label = ctk.CTkLabel(self, text="3. Select Starting Image (for SVD):", font=("Arial", 14, "bold"))
        self.image_label.pack(pady=(20, 5), padx=20, anchor="w")
        
        self.image_btn = ctk.CTkButton(self, text="Browse Image", command=self.select_image, fg_color="gray40", hover_color="gray30")
        self.image_btn.pack(pady=5, padx=20, anchor="w")
        
        self.image_preview_label = ctk.CTkLabel(self, text="No image selected")
        self.image_preview_label.pack(pady=5, padx=20, anchor="w")

        # 4. Prompt
        self.prompt_label = ctk.CTkLabel(self, text="4. Enter Prompt (for LTX):", font=("Arial", 14, "bold"))
        self.prompt_label.pack(pady=(20, 5), padx=20, anchor="w")
        
        self.prompt_entry = ctk.CTkTextbox(self, height=80, width=560)
        self.prompt_entry.pack(pady=5, padx=20)

        # 5. Generate Button
        self.generate_btn = ctk.CTkButton(self, text="🚀 Generate Video", command=self.start_generation, height=50, font=("Arial", 16, "bold"))
        self.generate_btn.pack(pady=(30, 10), padx=20)
        
        self.status_label = ctk.CTkLabel(self, text="", text_color="yellow", font=("Arial", 12))
        self.status_label.pack(pady=5, padx=20)

    def select_image(self):
        file_path = filedialog.askopenfilename(filetypes=[("Image Files", "*.png *.jpg *.jpeg")])
        if file_path:
            self.image_path = file_path
            self.image_preview_label.configure(text=f"Selected: {os.path.basename(file_path)}")

    def start_generation(self):
        url = self.url_entry.get().strip()
        model = self.model_var.get()
        prompt = self.prompt_entry.get("1.0", "end-1c").strip()
        image = self.image_path

        if not url:
            messagebox.showerror("Error", "Please paste the Gradio Link first!")
            return
            
        if "colab.research.google.com" in url or "huggingface.co" in url:
            messagebox.showerror("Wrong Link", "Oops! You pasted the Google Colab Notebook link.\n\nYou need to paste the Gradio Live link.\n1. Click the Open Colab button.\n2. In Colab, click 'Run All'.\n3. Wait for the cell at the bottom to finish loading.\n4. Copy the link that looks like 'https://xxxxxx.gradio.live' and paste it here.")
            return

        if model == "Stable Video Diffusion (Image-to-Video)" and not image:
            messagebox.showerror("Error", "Please select an image for SVD!")
            return
            
        if "LTX-Video" in model and not prompt:
            messagebox.showerror("Error", "Please enter a prompt for LTX-Video!")
            return

        self.generate_btn.configure(state="disabled", text="⏳ Generating... Please wait (might take minutes)")
        self.status_label.configure(text="Sending request to Colab...")
        
        # Run in background thread to avoid freezing UI
        threading.Thread(target=self.generate_video_task, args=(url, model, prompt, image), daemon=True).start()

    def generate_video_task(self, url, model, prompt, image):
        try:
            client = Client(url)
            
            # Map input to gradio predict
            self.status_label.configure(text="Processing on cloud GPU...")
            
            img_input = handle_file(image) if image else None
            
            result_video_path = client.predict(
                image=img_input,
                prompt=prompt,
                model_choice=model,
                api_name="/predict"
            )
            
            # Copy result to app folder
            app_folder = os.path.dirname(os.path.abspath(__file__))
            final_path = os.path.join(app_folder, "Generated_Video.mp4")
            
            # If multiple generations, append numbers
            counter = 1
            while os.path.exists(final_path):
                final_path = os.path.join(app_folder, f"Generated_Video_{counter}.mp4")
                counter += 1
                
            shutil.copy(result_video_path, final_path)
            
            self.status_label.configure(text=f"✅ Done! Saved as {os.path.basename(final_path)}")
            messagebox.showinfo("Success!", f"Video generated and saved in the app folder as:\n{os.path.basename(final_path)}")
            
        except Exception as e:
            self.status_label.configure(text="❌ Error occurred")
            messagebox.showerror("Generation Error", f"Could not generate video. Check Colab link or Colab logs.\nError: {str(e)}")
            
        finally:
            self.generate_btn.configure(state="normal", text="🚀 Generate Video")

if __name__ == "__main__":
    app = VideoApp()
    app.mainloop()